# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_auto_20170327_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
