# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_auto_20170327_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.URLField(max_length=256),
        ),
    ]
